
services:
  db:
    image: mongo:latest
    container_name: smarttask-db
    networks:
      - smarttask-net
    volumes:
      - smarttask-db-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    image: smarttask-backend:v1
    container_name: smarttask-backend
    networks:
      - smarttask-net
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://smarttask-db:27017/smarttask
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: smarttask-frontend:v1
    container_name: smarttask-frontend
    networks:
      - smarttask-net
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  smarttask-net:
    driver: bridge

volumes:
  smarttask-db-data:
